### ISSUE TITLE
Quantify command error with f relation in Allen algebra

### ISSUE THREAD

**Issue by johanmazelanssi** [dwolter/SparQ#7]
I compiled SparQ on a Debian testing.
`gcc -v` and `g++ -v` yields:
`gcc version 9.3.0 (Debian 9.3.0-13)`
Libtool package version is 2.4.6-14
Sbcl package version is 2:2.0.5-1.

On my machine, I get the following results:
* `./sparq quantify allen "((i0 fi i1))"` yields `((i1 2 3) (i0 1 3))`.
* `./sparq quantify allen "((i0 f i1))"` yields `((i1 1 2) (i0 3 4))`.
In the second case, it looks like i0 and i1 do not finish at the same time. It however should be the case for relation f.

**Comment by dwolter** [comment]
Thanks for reporting. The error is now fixed.
